apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-virtualcluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
{{- with ( include "unikorn.imagePullSecrets" . ) }}
imagePullSecrets:
{{ . }}
{{- end }}
