apiVersion: unikorn-cloud.org/v1alpha1
kind: ClusterManagerApplicationBundle
metadata:
  name: cluster-manager-1.0.0
spec:
  version: 1.0.0
  applications:
  - name: vcluster
    reference:
      kind: HelmApplication
      name: vcluster
      version: 0.15.7
  - name: cert-manager
    reference:
      kind: HelmApplication
      name: cert-manager
      version: v1.14.5
  - name: cluster-api
    reference:
      kind: HelmApplication
      name: cluster-api
      version: v0.1.11
