apiVersion: v2
name: unikorn-kubernetes
description: A Helm chart for deploying Unikorn Kubernetes Service

type: application

version: v1.0.0-rc1
appVersion: v1.0.0-rc1

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.15
  repository: https://unikorn-cloud.github.io/helm-common
