apiVersion: v2
name: unikorn-kubernetes
description: A Helm chart for deploying Unikorn Kubernetes Service

type: application

version: v1.0.0-rc2
appVersion: v1.0.0-rc2

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.15
  repository: https://nscaledev.github.io/uni-helm-common
