apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
{{- with ( include "unikorn.imagePullSecrets" . ) }}
imagePullSecrets:
{{ . }}
{{- end }}
