apiVersion: v2
name: unikorn
description: A Helm chart for deploying Unikorn

type: application

version: v0.2.1
appVersion: v0.2.1

icon: https://raw.githubusercontent.com/unikorn-cloud/unikorn/main/icons/default.png
